# Pruebas

Matias

In [1]:
import pandas as pd
import numpy as np
import requests
from src.data_loader import _load_single_gsheet, _get_gsheet_client, _load_single_gsheet_ci
from src.limpieza import limpiar_consumos
from src import config

2026-03-24 16:44:48.003 WARNING streamlit.runtime.caching.cache_data_api: No runtime found, using MemoryCacheStorageManager

In [2]:
df = limpiar_consumos(_load_single_gsheet( client=_get_gsheet_client(), sheet_id= config.GSHEET_IDS["CONSUMO"], sheet_name = "OWTR"))

2026-03-24 16:44:48.018 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-24 16:44:48.491
Warning: the config option 'server.enableCORS=false' is not compatible with
'server.enableXsrfProtection=true'.
As a result, 'server.enableCORS' is being overridden to 'true'.

More information:
In order to protect against CSRF attacks, we send a cookie with each request.
To do so, we must specify allowable origins, which places a restriction on
cross-origin resource sharing.

If cross origin resource sharing is required, please disable server.enableXsrfProtection.

2026-03-24 16:44:48.492
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\m.fernandez_fluxsola\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-03-24 16:44:48.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-24 16:44:48.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-24 16:44:48.494 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-24 16:44:48.902 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-24 16:44:48.903 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-24 16:44:48.904 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

In [3]:
df.head()

,NumSolicitud,FechaSolicitud,SolicitadoPor,CodigoArticulo,NombreArticulo,GrupoArticulo,Familia_Articulo,SubFamilia,CantidadSolicitada,BodegaOrigen_Solicitada,BodegaDestino_Requerida,CostoUnitarioEstimado,ValorTotalSolicitado,CodigoProyecto,NombreProyecto,CodigoUnidadNegocio,NombreUnidadNegocio
2248,100004169,2025-03-03,Roberto Videla,EXI-008654,Solis Medidor DDSD1352-C Single Phase + Cts,EXISTENCIA,EQUIPOS PRINCIPALES,ACCESORIOS,1.0,Bodega Fluxsolar,Bodega de Proyectos RE,0.0,0.0,RVDIC-751,PR IND GERARDO GUZMAN,RE,RESIDENCIAL
2249,100004169,2025-03-03,Roberto Videla,EXI-009536,Hp Conector Perfil Ult,EXISTENCIA,EQUIPOS PRINCIPALES,ESTRUCTURAS,4.0,Bodega Fluxsolar,Bodega de Proyectos RE,743.0,0.0,RVDIC-751,PR IND GERARDO GUZMAN,RE,RESIDENCIAL
2250,100004169,2025-03-03,Roberto Videla,EXI-009535,Hp Perfil Ult 4700Mm,EXISTENCIA,EQUIPOS PRINCIPALES,ESTRUCTURAS,5.0,Bodega Fluxsolar,Bodega de Proyectos RE,0.0,0.0,RVDIC-751,PR IND GERARDO GUZMAN,RE,RESIDENCIAL
2251,100004169,2025-03-03,Roberto Videla,EXI-008846,Panel Solar Longi 500W Lr5-66Hph (Revalorizado...,EXISTENCIA,EQUIPOS PRINCIPALES,PANELES,10.0,Bodega Fluxsolar,Bodega de Proyectos RE,0.0,0.0,RVDIC-751,PR IND GERARDO GUZMAN,RE,RESIDENCIAL
2252,100004169,2025-03-03,Roberto Videla,EXI-008341,Solis Accesorio S2-Wl-St (Wifi Stick),EXISTENCIA,EQUIPOS PRINCIPALES,ACCESORIOS,1.0,Bodega Fluxsolar,Bodega de Proyectos RE,0.0,0.0,RVDIC-751,PR IND GERARDO GUZMAN,RE,RESIDENCIAL

In [4]:
df_panel = df[df.NombreArticulo == "Panel Solar Longi LR7-72HVD -650W Bifacial"]

In [6]:
df_panel.groupby(["NombreArticulo", "BodegaDestino_Requerida"])["CantidadSolicitada"].sum().reset_index()

,NombreArticulo,BodegaDestino_Requerida,CantidadSolicitada
0,Panel Solar Longi LR7-72HVD -650W Bifacial,Bodega de Proyectos CI VDI,4838.0
1,Panel Solar Longi LR7-72HVD -650W Bifacial,Bodega de Proyectos ESCO & PPA,2989.0
2,Panel Solar Longi LR7-72HVD -650W Bifacial,Bodega de Proyectos LEAS & BOOT,648.0
3,Panel Solar Longi LR7-72HVD -650W Bifacial,Bodega de Proyectos RE,54.0

In [7]:
2989*0.015

44.835

In [9]:
consumos_producto = df_raw.groupby(["NombreArticulo"])["CantidadSolicitada"].sum()
consumos_producto

NombreArticulo
AMPERE SEMS BUFFER SLIM 100 kW 120kWh NARADA                                                                1
Ampere Celda                                                                                             1022
Ampere T-Pro 36                                                                                            19
Ampere Tower ProM 0.6 (sin bateria)                                                                      5141
Antai Estructura Fija Biposte 2V18 c/tornillo de 1,8m                                              9101611616
                                                                                  ...
Solis Solar Inverter S6-Gr1P6K 1 Ph 2 Mppt Dc Meter Port    1111111111111111111111111111111111111111111111...
Spare part NARADA 133 kWh                                                                                   1
Tapa Frontal Zocalo 709180 Teos/Neo Ancho 800mm 2 Pcs                                                       4
Tfv Socreyco                                                                                                1
Tracker Pmgd Cousiñi Skysmart II Single Row                                                                 1
Name: CantidadSolicitada, Length: 139, dtype: object

In [29]:
print(consumos_producto["Tfv Socreyco"])

4

In [33]:
consumos_producto_fecha = df_consumo.groupby(["NombreArticulo", "FechaSolicitud"])["CantidadSolicitada"].sum()
consumos_producto_fecha

NombreArticulo                                         FechaSolicitud
*Hdt Huawei Inversor Sun2000-50Ktl-M3                  2024-01-30        1
                                                       2024-03-11        3
                                                       2024-03-18        1
                                                       2024-03-21        1
                                                       2024-03-22        1
                                                                        ..
Tapa Frontal Zocalo 709180 Teos/Neo Ancho 800mm 2 Pcs  2024-02-19        4
Tfv Socreyco                                           2024-01-26        1
                                                       2024-04-05        3
Tracker Pmgd Cousiñi Skysmart II Single Row            2025-12-12        1
                                                       2026-01-15        1
Name: CantidadSolicitada, Length: 5378, dtype: int64

In [39]:
consumos_producto_fecha["*Hdt Huawei Inversor Sun2000-50Ktl-M3"].sum()

np.int64(68)